#!/bin/sh

# script to launch stuff from dwm, so I can keep a local config of which actual programs to launch without
# changing my global config and tracking that...

terminal="lxterminal"
lockscreen="lockscreen.sh"
launcher="bashrun"


if [ -f $HOME/.dwmlaunch.local ]
then
    source $HOME/.dwmlaunch.local
fi


case $1 in
terminal )
    exec $terminal ;;
lockscreen )
    exec $lockscreen ;;
launcher )
    exec $launcher ;;
esac

echo 1>&2 "dwmlaunch cammand not found: $1"

