#!/bin/sh

# Script to put symlinks for dotfiles
# assumes my dotfiles git repo is at $HOME/dotfileswgh

dostuff() {
    stow --no-folding --restow homedir
    # Make sundry directories and files so things (especially vim) don't complain
    # and stuff that I just like to be there in general
    mkdir -p $HOME/.cache/vimtmp
    # the cache could hold sensitive stuff
    chmod 700 $HOME/.cache
    mkdir -p $HOME/prifs
    chmod 700 $HOME/prifs
    # konsole is always changing this, and it's annoying.
    chmod 444 config/konsolerc
    mkdir -p $HOME/dl # my default download directory
    mkdir -p $HOME/vserv-mount
    mkdir -p $HOME/tmp
    mkdir -p $HOME/.themes
    mkdir -p $HOME/.config
    mkdir -p $HOME/.themes
    # dirs for mpd
    mkdir -p $HOME/.cache/mpd/playlists
    mkdir -p $HOME/.cache/mutt
    mkdir -p $HOME/musc-local
    mkdir -p dotlocal/firefox-default-profile
    ln -sf ../../../usercss dotlocal/firefox-default-profile/chrome/usercss
    echo '@import url("./usercss/master.css")' > dotlocal/firefox-default-profile/chrome/userContent.css
    mkdir -p dotlocal/firefox-noaddon-profile

    # get terminfo set up
    tic -x xterm-256color-italic.terminfo
    tic -x xterm-24bit.terminfo
    tic -x xterm-24bit-italic.terminfo
}


#######################################

if [ "s-$1" = "s-do" ]
then
    dostuff
else
    echo "usage: linkup.bash < do >"
    echo "       Be sure to run this IN the dotfileswgh directory."
fi

