#!/bin/sh

# Script to put symlinks for dotfiles
# assumes my dotfiles git repo is at $HOME/dotfileswgh

dostuff() {
    stow --no-folding --restow homedir
    # Make sundry directories and files so things (especially vim) don't complain
    # and stuff that I just like to be there in general
    mkdir -p $HOME/.cache/vimtmp
    # the cache could hold sensitive stuff
    chmod 700 $HOME/.cache
    mkdir -p $HOME/prifs
    chmod 700 $HOME/prifs
    mkdir -p $HOME/dl # my default download directory
    mkdir -p $HOME/.themes
    mkdir -p $HOME/.config
    # dirs for mpd
    mkdir -p $HOME/.cache/mpd/playlists
    mkdir -p $HOME/.cache/mutt
    mkdir -p $HOME/musc-local
    mkdir -p dotlocal/firefox-default-profile
    mkdir -p dotlocal/firefox-default-profile/chrome
    ln -sf ../../../usercss dotlocal/firefox-default-profile/chrome/usercss
    echo '@import url("./usercss/master.css")' > dotlocal/firefox-default-profile/chrome/userContent.css

    # get terminfo set up
    tic -x xterm-256color-italic.terminfo
    tic -x xterm-24bit.terminfo
    tic -x xterm-24bit-italic.terminfo

    # Some programs like to modify config files without asking me about it.  Usually the diffs are for very unimportant things, or they can't keep separation between proper config and state (eg. last UI state) that they want to save.  Let's make some files read-only to stop getting stupid git changes.
    chmod 444 config/konsolerc
    chmod 444 config/htop/htoprc
    chmod 444 homedir/.mozilla/firefox/profiles.ini
}


#######################################

if [ "s-$1" = "s-do" ]
then
    dostuff
else
    echo "usage: linkup.bash < do >"
    echo "       Be sure to run this IN the dotfileswgh directory."
fi

