#!/bin/sh

if [ -z "$XSESSION_COMMON_RUN_P" ]; then

  source $DOTFILESWGH/env-more.sh

  busdir=$XDG_RUNTIME_DIR/dbus-session-bus-addresses/
  mkdir -p $busdir
  echo "${DBUS_SESSION_BUS_ADDRESS}" >"$busdir/tty_${LOGIN_TTY}"

  # Gnome programs can dynamically switch between light and dark if an xsettings daemon is running.
  # By default in gnome this is gsd-xsettings, but xsettingsd can be used with other window managers.
  # I'm not sure how to do this on wayland.
  xsettingsd-wrapper --start &

  ### light/dark theming
  # The default is dark if nothing is written to the status file, so this will default dark without writing anything.
  # This also runs xrdb for xresources.
  lightdark-status soft-update


  # hack to fix pulseaudio, which doesn't seem to work for some reason...
  {
    killall pulseaudio
    sleep 4
    pulseaudio
  } &

  # get keyboard layout
  hkk
  # set sticky keys, don't cancel sticky keys if two keys are pressed at once, allow latch-to-lock
  xkbset sticky -twokey latchlock

  # Control mouse with keyboard
  keynav &

  # Unclutter hides the mouse pointer after the given number of seconds
  unclutter -idle 5 &

  # set the screen layout -- IE detect how many monitors I have connected and adjust
  # this script should live in one of my local script directories on my path
  screenlayout-default.sh

  # Backround
  {
      while true; do
          wallpaper-set-random
          # 600 seconds = 10 minutes
          sleep 600
      done
  }&

  #cinnamon-screensaver &
  xscreensaver -no-splash &

  #### touchpad config
  # turn off tap-to-click
  synclient maxtaptime=0
  # allow horizontal two-finger scroll
  synclient HorizTwoFingerScroll=1


  # Be sure I have a decent terminfo available
  tic $DOTFILESWGH/xterm-256color-italic.terminfo

  # Notifications
  dunst &
  dunst-lock-monitor &

  mpd &

  # Compositing for eg. transparent terminals
  #xcompmgr &
  picom &

  # application tray
  # good trayer command
  #trayer --edge top --align right --width 10 --height 12 --transparent true --alpha 255 &
  nm-applet &
  #blueman-applet &
  blueberry-tray &

  #unicoder_socket="/tmp/the-unicoder_${USER}_${DISPLAY/:/}"
  unicoder_socket="5782"
  #rm -f "$unicoder_socket"
  racket -l the-unicoder -- --server --port "$unicoder_socket" &

  #libnotifylogger.py $HOME/.cache/notifications.log &

  # Watch keyboard state for awesome
  $DOTFILESWGH/config/awesome/kbd-state-mon.sh &

  # start kdeconnect daemon, let my phone drive
  #kdeconnect-cli

  # move the mouse out of the middle of the screen so it won't switch windows for no reason
  xdotool mousemove 100 100

  if [ -e "$DOTFILESWGH/dotlocal/e-is-premacs" ]; then
    premacs-init &
  fi


  if [ -f $DOTFILESWGH/pri/xinitrc ]; then
      source $DOTFILESWGH/pri/xinitrc
  fi
  if [ -f $DOTFILESWGH/dotlocal/xinitrc ]; then
      source $DOTFILESWGH/dotlocal/xinitrc
  fi

fi
export XSESSION_COMMON_RUN=true
