#!/usr/bin/env bash

# lightdark update for hyprland
if [[ -n "$1" ]]; then
    mode="$1"
else
    mode="$(lightdark-status)"
fi

if [[ "$mode" = "light" ]]; then
    hyprctl keyword general:col.active_border "rgba(336cfdee)"
    #hyprctl setcursor phinger-cursors-dark ${XCURSOR_SIZE:-32}
    #hyprctl setcursor phinger-cursors-light ${XCURSOR_SIZE:-32}
    #hyprctl setcursor catppuccin-frappe-green ${XCURSOR_SIZE:-32}
    #hyprctl setcursor ComixCursors-Green ${XCURSOR_SIZE:-32}
else
    hyprctl keyword general:col.active_border "rgba(33ccffee) rgba(00ff99ee) 45deg"
    #hyprctl setcursor phinger-cursors-dark ${XCURSOR_SIZE:-32}
    #hyprctl setcursor phinger-cursors-light ${XCURSOR_SIZE:-32}
    #hyprctl setcursor catppuccin-latte-green ${XCURSOR_SIZE:-32}
    #hyprctl setcursor ComixCursors-Green ${XCURSOR_SIZE:-32}
fi

