#!/usr/bin/env bash

# wrapper for my most common usage of awk, because I always
# forget its syntax.

if [[ "$@" =~ "--help" ]]; then
    echo "Usage: $0 <field_num> [field_num ...]"
    echo "Reads from stdin"
    exit 0
fi

awkcmd='{print $'"$1"
shift

for x in $@; do
    awkcmd=${awkcmd}',$'${x}
done
awkcmd=${awkcmd}'}'

awk "$awkcmd" <&0
