#!/usr/bin/env bash

# wrapper for my most common usage of awk, because I always
# forget its syntax.

awkcmd='{print $'"$1"
shift

for x in $@; do
    awkcmd=${awkcmd}',$'${x}
done
awkcmd=${awkcmd}'}'

awk "$awkcmd" <&0
