#!/usr/bin/env bash
#
# battery status script
#

# BATTERY=/proc/acpi/battery/BAT0
BATTERY=/sys/class/power_supply/BAT0

REM_CAP="$(cat $BATTERY/charge_now)"
FULL_CAP="$(cat $BATTERY/charge_full)"
BATSTATE="$(cat $BATTERY/status)"

CHARGE=`echo $(( $REM_CAP * 100 / $FULL_CAP ))`

NON='\033[00m'
BLD='\033[01m'
RED='\033[01;31m'
GRN='\033[01;32m'
YEL='\033[01;33m'

GRN='\033[01;32m'
YEL='\033[01;33m'

COLOUR="$RED"

case "${BATSTATE}" in
   'Full')
   BATSTT="$BLD=$NON"
   ;;
   'Charging')
   BATSTT="$BLD+$NON"
   ;;
   'Discharging')
   BATSTT="$BLD-$NON"
   ;;
   'Not charging')
   BATSTT="$BLD~$NON"
   ;;
esac


if [ "$CHARGE" -gt "25" ]
then
   COLOUR="$YEL"
fi

if [ "$CHARGE" -gt "50" ]
then
   COLOUR="$GRN"
fi

echo -e "${COLOUR}${CHARGE}${NON}${BATSTT}"
