#!/usr/bin/env bash

if [[ "$@" =~ "--help" ]]; then
    cat $(readlink -f "$0")
    exit 0
fi

lightdark=$(state lightdark)
CDIR=$DOTFILESWGH/alacritty
cat $CDIR/base-config.yml $CDIR/theme-${lightdark}.yml > $XDG_RUNTIME_DIR/alacritty-config.yml
