#!/usr/bin/env bash

unset DOTFILESWGH
unset DOTFILESWGH_DOTLOCAL
unset DOTFILESWGH_PRI
unset DOTFILESWGH_PRI_DOTLOCAL
unset WGHHOME
if [[ -d "$HOME/dotfileswgh" ]]; then
    export DOTFILESWGH="$HOME/dotfileswgh"
elif [[ -d /rootgit/base.rootgit/dotfileswgh ]]; then
    export DOTFILESWGH=/rootgit/base.rootgit/dotfileswgh
else
    echo no dotfileswgh found
    exit 1
fi

#source $DOTFILESWGH/env-basic.sh
#source $DOTFILESWGH/env-more.sh
#exec "$@"

echo "$DOTFILESWGH"
