#!/usr/bin/env racket
#lang racket/base
(require
 gregor
 racket/cmdline
 "../racket-libs/exec/main.rkt"
 )

(define specs
  (command-line #:args specs
                specs))

(define offsets (if (null? specs)
                    '(0)
                    (map string->number specs)))

(define dates (map (λ (off) (+days (today) off)) offsets))

(define (date->str d)
  (~t d "YYYY-MM-dd"))

(define filenames (map (λ (date) (format "~a.org" (date->str date))) dates))

(apply execv (find-executable-path "e") filenames)
