#!/usr/bin/env racket
#lang rash
(require
 gregor
 racket/cmdline
 )

(define specs
  (command-line #:args specs
                specs))

(define offsets (if (null? specs)
                    '(0)
                    (map string->number specs)))

(define dates (map (λ (off) (+days (today) off)) offsets))

(define (date->str d)
  (~t d "YYYY-MM-dd"))

(define filenames (map (λ (date) (format "~a.org" (date->str date))) dates))


e $filenames
