#!/usr/bin/env racket
#lang rash
(require
 gregor
 racket/cmdline
 )

(define specs
  (command-line #:args specs
                specs))

(define week-ns (if (null? specs)
                    '(0)
                    (map string->number specs)))

(define ts (map (λ (week-n) (+weeks (today) week-n)) week-ns))

(define start-of-week (map (λ (t) (-days t (->wday t))) ts))
(define end-of-week (map (λ (t) (+days t (- 6 (->wday t)))) ts))

(define (date->str d)
  (~t d "YYYY-MM-dd"))

(define filenames (map (λ (start-of-week end-of-week)
                         (format "~a_to_~a.org"
                                 (date->str start-of-week)
                                 (date->str end-of-week)))
                       start-of-week
                       end-of-week))


e $filenames
