#!/usr/bin/env bash

if [[ "$@" =~ "--help" ]]; then
    cat $(readlink -f "$0")
    exit 0
fi

mkdir -p /tmp/$USER
file=/tmp/$USER/current-mpc
current=$(cat $file 2>/dev/null)
current="${current:-mpcl}"

if [[ -z "$1" ]]; then
  echo $current
else
  echo "$1" > $file
fi
