#!/usr/bin/env bash

#old_unread=$(unread-hatchmail-count)
offlineimap -c $DOTFILESWGH/pri/hatchmail-offlineimap.conf
#new_unread=$(unread-hatchmail-count)
#diff_unread=$(( $new_unread - $old_unread ))
#
#if [[ "$diff_unread" -gt 0 ]]; then
#    if [[ -z "$DISPLAY" ]]; then
#        export DISPLAY=":0"
#    fi
#    notify-send "$diff_unread new email(s)"
#fi


