#!/usr/bin/env bash
if [[ "$(cat $DOTFILESWGH_DOTLOCAL/background-sync 2>/dev/null)" = "true" ]]; then
  exec "$@"
else
  echo "background-sync disabled, relevant env: DOTFILESWGH_DOTLOCAL = '$DOTFILESWGH_DOTLOCAL'" >&2
  exit
fi
