#!/usr/bin/env bash

help() {
    echo "Usage: $0 [dark|light|toggle|status]"
    echo "Gives status if called with no argument or the status argument."
    echo "Sets status if called with light, dark, or toggle."
    exit 1
}

# Using a user-specific directory is annoying when I run stuff with sudo.  So let's just use a global file for all users, because realistically it's just me.
#lddir="${XDG_RUNTIME_DIR:-/tmp/$USER}"
lddir="/tmp"
mkdir -p $lddir
ldfile="$lddir/lightdark"
lightdark="$WGH_THEME_DARK_OR_LIGHT"
lightdark="${lightdark:-$(cat $ldfile 2>/dev/null)}"
lightdark=${lightdark:-dark}

update(){
    # $1 is either "light" or "dark"
    mkdir -p $lddir
    echo "$1" > "$ldfile"
    lightdark-konsole-dbus-update
    # gsettings dynamically sets running gtk3 programs that are connected to the gsd-xsettings daemon (gnome-settings-daemon)
    # The well-supported dark/light themes are Yaru-dark and Yaru-light
    #gsettings set org.gnome.desktop.interface gtk-theme Yaru-$1
    # Alternatively, we can set that theme using xsettings instead.
    xsettingsd-wrapper
    echo "$1"
}

if [[ "$#" = 0 ]]; then
    exec echo "$lightdark"
    exit 0
elif [[ "$#" = 1 ]]; then
    if [[ "$1" = "light" || "$1" = "dark" ]]; then
        update "$1"
        exit 0
    elif [[ "$1" = "toggle" ]]; then
        if [[ "$lightdark" = "light" ]]; then
            update dark
            exit 0
        else
            update light
            exit 0
        fi
    elif [[ "$1" == "status" ]]; then
        echo "$lightdark"
        exit 0
    fi
fi

# Print help if argument wasn't one of "light", "dark", or "toggle".

help
