#!/bin/sh

if [ -z "$DISPLAY" ]; then
    # since I'm making a notification for myself, I
    # probably want it displayed -- the 'at' command
    # doesn't preserve the display variable, so I'll
    # make a reasonable assumption.
    DISPLAY=":0"
    export DISPLAY
fi

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    # get the bus address that I've stashed in xinitrc
    export "$(cat /tmp/wgh/tty/dev/tty1/dbus-session-bus-address)"
fi

notify-send "Note" "$*"

