#!/usr/bin/env bash

if [[ "$@" =~ "--help" ]]; then
    echo "Usage: $0 [files...]"
    echo "Use a premacs emacs daemon as a pager, reading stdin into a temporary file."
    exit 0
fi

export ALTERNATE_EDITOR=less
dir="${XDG_RUNTIME_DIR:-/tmp/$(whoami)}/premacs-pages"
mkdir -p "$dir"
chmod 700 "$dir"
tmpf="$(mktemp $dir/pager-XXXXXX)"
cat <&0 >"$tmpf"

if premacs-get-next-daemon >/dev/null; then
  daemon="$(premacs-get-next-daemon)"
  emacsclient -e '(setq start-on-pager-state t)' -s "$daemon" >/dev/null
fi

premacs-use-t "$tmpf" "$@"

rm "$tmpf"

