#!/usr/bin/env bash

daemon="$(premacs-get-next-daemon)"

if [[ "none" = "$daemon" ]]; then
    # rather than die, fall back on ALTERNATE_EDITOR
    exec emacsclient -nw "$@"
fi

old=/tmp/$(whoami)/premacs
new=/tmp/$(whoami)/premacs-tmp
mv "$old" "$new"
grep -v "$daemon" "$new" > "$old"
rm "$new"

premacs-new >/dev/null 2>&1 &

emacsclient -e "(setenv \"PWD\" \"$PWD\")" -s "$daemon" >/dev/null
emacsclient -s "$daemon" "$@"
emacsclient -e '(kill-emacs)' -s "$daemon"


