#!/usr/bin/env bash

if [[ "$@" =~ "--help" ]]; then
    echo "Usage: $0 <elisp-expression>"
    echo "Evaluate an elisp expression using a premacs daemon, or batch emacs if none available."
    exit 0
fi

echo premacs-use-for-script got: $@
script="$1"

daemon="$(premacs-use-next-daemon)"

if [[ "none" = "$daemon" ]]; then
    emacs --batch -l $DOTFILESWGH/emacs/def.el --eval "$script"
    exit
fi

emacsclient --eval "$script" -s "$daemon"

emacsclient -e '(kill-emacs)' -s "$daemon"
