#!/usr/bin/env bash

daemon="$(premacs-get-next-daemon)"

if [[ "none" = "$daemon" ]]; then
    # rather than die, fall back on ALTERNATE_EDITOR
    exec emacsclient -nw "$@"
fi

premaxd=${XDG_RUNTIME_DIR:-/tmp/$(whoami)}/
old=$premaxd/premacs-list
new=$premaxd/premacs-tmp
mv "$old" "$new"
grep -v "$daemon" "$new" > "$old"
rm "$new"

premacs-new >/dev/null 2>&1 &

emacsclient -e "(setenv \"PWD\" \"$PWD\")" -s "$daemon" >/dev/null
emacsclient -e "(with-current-buffer \"*scratch*\" (cd \"$PWD\"))" -s "$daemon" >/dev/null
if [[ "$(lightdark-status)" = "light" ]]; then
    emacsclient -e "(light-theme)" -s "$daemon" >/dev/null
else
    emacsclient -e "(dark-theme)" -s "$daemon" >/dev/null
fi
# The next line adds the given arguments.  If given `-t`, as in premacs-use-t, it will open a terminal, if given `-c` it will open a gui.  If not given one of those, it will send a command without doing anything else.  Importantly, the `-e` argument here is run after the terminal is initiated, so things that modify terminal state are effective here.
emacsclient -e "(disable-csi-u-key-encoding)" -s "$daemon" "$@"
emacsclient -e '(kill-emacs)' -s "$daemon"


