#!/usr/bin/env bash

# script to pre-launch emacs daemons to speed up start time

if [[ "$@" =~ "--help" ]]; then
    echo "Usage: $0"
    echo "Force-start new premacs emacs daemons regardless of current pool state."
    exit 0
fi

premacs-new &
premacs-new &
premacs-new

echo "premacs ready!"

