#!/usr/bin/env bash

if [[ -z "$CURRENT_DEV_MODE" && -e "$DOTFILESWGH_DOTLOCAL/e-is-premacs" && ! "$(whoami)" = "root" ]]; then
    exec premacs-use-or-create-t "$@"
fi

#exec em "$@"
SHELL=/bin/sh exec emacs --eval '(setq wgh/fast-start t)' -nw -q -l $DOTFILESWGH/emacs/def "$@"
