#!/bin/sh

for daemon in `ls /tmp/emacs*/premacs*`
do
    emacsclient -e '(kill-emacs)' -s $daemon
done

ps aux | grep emacs | grep daemon | grep premacs | awk '{print $2}' | xargs kill -9

rm /tmp/premacs

