#!/usr/bin/env bash

# start up new emacs daemon

export SHELL=/bin/sh
premaxd=${XDG_RUNTIME_DIR:-/tmp/$(whoami)}
newId=$RANDOM
daemon=$premaxd/premacs-socket-$newId
EDIR=$DOTFILESWGH/emacs
cd $HOME
mkdir -p "$premaxd"
emacs -l $EDIR/def.el -l $EDIR/premacs-run.el "--daemon=$daemon" && \
echo $daemon >> "$premaxd/premacs-list"

