#!/usr/bin/env bash

echo premacs-use-for-script got: $@
script="$1"

daemon="$(premacs-use-next-daemon)"

if [[ "none" = "$daemon" ]]; then
    emacs --batch -l $DOTFILESWGH/emacs/def.el --eval "$script"
    exit
fi

emacsclient --eval "$script" -s "$daemon"

emacsclient -e '(kill-emacs)' -s "$daemon"
