#!/usr/bin/env bash

# start up new emacs daemon

newId=$RANDOM
EDIR=$DOTFILESWGH/emacs
cd $HOME
emacs -l $EDIR/def.el -l $EDIR/premacs-run.el --daemon=premacs$newId && \
echo premacs$newId >> /tmp/$(whoami)/premacs
