#!/bin/bash

# The >> operator is great for appending, but sometimes what you really
# need to do is prepend.

if [ -z "$1" ]; then
    echo "usage, taking prepended text from stdin:  prepend <file>"
    exit
fi

tmpname=$(mktemp /tmp/$(basename "$1")_prepend_tmp_file_XXXXXX)

cat - "$1" > "$tmpname" && mv "$tmpname" "$1"

