#!/bin/sh

# Pretty print files that are often ugly.

usage(){
    echo "usage: $0 <xml|json>"
}

if [ "$1" = "json" ]; then
    python -m json.tool <&0
elif [ "$1" = "xml" ]; then
    xmllint --format - <&0
else
    usage
fi
