#!/bin/sh
# TODO - this is a copy of rpdev, and should be merged...

if test -f /etc/NIXOS; then
  exec nix-shell '<nixpkgs>' --command rcdev.rkt --packages bashInteractive racket cairo fontconfig glib gmp gtk2 libedit libjpeg libpng mpfr openssl pango poppler readline sqlite coreutils readline
else
  exec rcdev.rkt "$@"
fi

