#!/usr/bin/env racket
#lang racket/base

(require setup/dirs)
(require racket/cmdline)
(require racket/string)
(require net/sendurl)

(define browser "firefox")
(define terms (command-line
               #:once-each
               [("--browser") b "which browser to use" (set! browser b)]
               #:args q-terms
               (string-join q-terms)))

(define browser-setting (cons (string-append browser " ") ""))

(define (get-query-url query)
  (string-append "file://" (path->string (find-doc-dir)) "/search/index.html?q=" query))


(external-browser browser-setting)
(send-url (get-query-url terms))

