#!/bin/sh
export CURRENT_DEV_PATH=""
export CURRENT_DEV_MODE=reach-core
export EMACS_DOT_D_PATH=$DOTFILESWGH/dotlocal/emacs.d_reach-core
export DEV_MODE_REACH=$HOME/s/mk/reach-lang
exec reach-dev-environment.sh fhs "$@"
