#!/bin/sh

if test -f /etc/NIXOS; then
  exec nix-shell '<nixpkgs>' --command rpdev.rkt --packages bashInteractive racket cairo fontconfig glib gmp gtk2 libedit libjpeg libpng mpfr openssl pango poppler readline sqlite coreutils readline emacs
else
  exec rpdev.rkt
fi


