#!/usr/bin/env bash

# runas/be script.
# I made them one because they would only differ by one line, but it
# means they need a symlink and have to test which name it runs as.
#
# This is a wrapper to su or sudo to another user (be and runas, respectively),
# but run with my config files.  It keeps all of my environment except a few
# variables, like home, username... which need to point to the new user for
# most purposes.
#
# This will always run me with zsh, and needs sudo access, not just su.  For
# when I don't have sudo, there is a similar be-su wrapper script.

if [[ "$1" = "--keep" ]]; then
    keep=true
    shift
fi

user="$1"
shift

HOME=$( getent passwd "$user" | cut -d: -f6 )
USER="$user"
USERNAME="$USER"
LOGNAME="$USER"
unset XDG_DOWNLOAD_DIR
unset XDG_RUNTIME_DIR
unset MAIL

if [[ "${0:$((${#0} - 2)):2}" = "be" ]]; then
    if [[ "$keep" = true ]]; then
        # keep zdotdir by going through bash... somehow that works.
        exec sudo -E -u $user bash --rcfile $DOTFILESWGH/bashrc -i -c zsh
    else
        DOTFILESWGH="$(detect-dotfileswgh)"
        exec sudo --preserve-env=DOTFILESWGH -u $user bash --rcfile $DOTFILESWGH/bashrc -i -c zsh
    fi
else
    if [[ "$keep" = true ]]; then
        exec sudo -E -u $user "$@"
    else
        DOTFILESWGH="$(detect-dotfileswgh)"
        exec sudo --preserve-env=DOTFILESWGH -u $user "$@"
    fi
fi

