#!/usr/bin/env bash


pulseaudio &

# merge xresources first, so other programs in this (xscreensaver) can get settings
xrdb $DOTFILESWGH/Xresources

# get keyboard layout
#hkk
export XKB_DEFAULT_LAYOUT=hatchak,us
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle

# set sticky keys, don't cancel sticky keys if two keys are pressed at once, allow latch-to-lock
#xkbset sticky -twokey latchlock

# Control mouse with keyboard
#keynav &

# Unclutter hides the mouse pointer after the given number of seconds
#unclutter -idle 5 &

# set the screen layout -- IE detect how many monitors I have connected and adjust
# this script should live in one of my local script directories on my path
#screenlayout-default.sh

# Backround
#{
#    while true; do
#        wallpaper-set-random
#        # 600 seconds = 10 minutes
#        sleep 600
#    done
#}&


#### touchpad config
# turn off tap-to-click
#synclient maxtaptime=0
# allow horizontal two-finger scroll
#synclient HorizTwoFingerScroll=1


# Be sure I have a decent terminfo available
tic $DOTFILESWGH/xterm-256color-italic.terminfo

# Notifications
dunst &

mpd &

# application tray
# good trayer command
#trayer --edge top --align right --width 10 --height 12 --transparent true --alpha 255 &
nm-applet &
blueman-applet &

unicoder_socket="/tmp/the-unicoder_${USER}_${DISPLAY/:/}"

rm -f "$unicoder_socket"
the-unicoder --server --path "$unicoder_socket" &

$DOTFILESWGH/external/misc/libnotifylog/libnotifylogger.py $HOME/.cache/notifications.log &

# Watch keyboard state for awesome
#$DOTFILESWGH/config/awesome/kbd-state-mon.sh &

# start kdeconnect daemon, let my phone drive
#kdeconnect-cli

exec sway
