#!/bin/sh
# Check for running swaylock first, to not double lock
if pidof swaylock; then
    exit 0
fi
exec swaylock --ignore-empty-password --indicator-caps-lock --show-failed-attempts --show-keyboard-layout --color 012323 --daemonize
