#!/usr/bin/env bash

if [[ "$@" =~ "--help" ]]; then
    echo "Usage: $0"
    echo "Launch swayidle with preconfigured lock, screen-off, and sleep timeouts."
    exit 0
fi

monitorOff='swaymsg "output * power off"'
monitorOn='swaymsg "output * power on"'
if [[ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]]; then
  monitorOff='hyprctl dispatch dpms off'
  monitorOn='hyprctl dispatch dpms on'
fi

# don't actually use monitorOff for now... it seems to be causing problems
# monitorOff='true'
# monitorOn='true'

lockTimeout=600
lockWarn=$(( $lockTimeout - 10 ))
monitorTimeout=900

exec swayidle -w \
	timeout $lockWarn 'lightdark-status-double-toggle.sh' \
	timeout $lockTimeout 'swaylock-configured' \
	timeout $monitorTimeout "$monitorOff" \
		resume "$monitorOn" \
	before-sleep 'swaylock-configured' &
