#!/usr/bin/env bash

monitorOff='swaymsg "output * power off"'
monitorOn='swaymsg "output * power on"'
if [[ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]]; then
  monitorOff='hyprctl dispatch dpms off'
  monitorOn='hyprctl dispatch dpms on'
fi

lockTimeout=600
lockWarn=$(( $lockTimeout - 10 ))
monitorTimeout=900

exec swayidle -w \
	timeout $lockWarn 'lightdark-status-double-toggle.sh' \
	timeout $lockTimeout 'swaylock-configured' \
	timeout $monitorTimeout "$monitorOff" \
		resume "$monitorOn" \
	before-sleep 'swaylock-configured' &
