#!/usr/bin/env bash

if [[ "$@" =~ "--help" ]]; then
    cat $(readlink -f "$0")
    exit 0
fi

if pidof waybar >/dev/null 2>/dev/null ; then
    pkill waybar
else
    waybar-configured >/dev/null 2>&1 &
    disown
fi
