#!/usr/bin/env bash

# It's nice to set keys on eg. window managers to launch programs.  But sometimes
# you want to launch different programs for the same purpose on different machines.
# You don't want to muck about with your WM config for each of these, though, especially
# if you're running something that's configured in source, like dwm or xmonad.
#
# This script is to be put in place of raw commands in such config files.  It has
# some likely portable defaults, and sources a config file (bash script) to set overrides.
# That way you can change the specific programs for any machine simply by putting one line
# in a local config file.  This keeps your WM config consistent and easy to keep in version
# control.
#
# To override which terminal to launch, put
# terminal="my-xterm"
# in ~/.vlaunchrc, $XDG_CONFIG_DIR/vlaunchrc, or in the file pointed at by the $VLAUNCHRC variable.


function scmd(){
    if [ -z "$(eval echo \$$1)" ]; then
        cmd=$1
        shift
        eval "$cmd=\"$@\""
    fi
}

scmd terminal "konsole"
scmd terminal2 "konsole"
scmd lockscreen "xscreensaver-command -lock"
scmd launcher "bashrun"
scmd calendar "xterm-pager cal $(date +%Y)"
scmd sysmonitor "xterm -e htop"
scmd mixer "xterm -e alsamixer"
if which pamixer >/dev/null 2>&1; then
    scmd volup "pamixer --increase 5"
    scmd voldown "pamixer --decrease 5"
    scmd volmute "pamixer --toggle-mute"
else
    scmd volup "amixer -q sset Master 5%+"
    scmd voldown "amixer -q sset Master 5%-"
    scmd volmute "amixer -q sset Master toggle"
fi
scmd volupS "amixer -q sset Master 5%+"
scmd voldownS "amixer -q sset Master 5%-"
scmd volmuteS "amixer -q sset Master toggle"
scmd ledmon "ledmon"
scmd tray "stalonetray -i 12 --window-type normal --window-strut none \
           --background black --icon-gravity NE"
scmd xmonadViewConfig "xterm-pager cat $HOME/.xmonad/xmonad.hs"

function xterm-pager(){
    if [ -z "$1" ]; then
        echo "usage: $0 <cmd>"
    fi
    if [ -z "$PAGER" ]; then
        PAGER=less
    fi

    file="/tmp/xterm-pager.tmp"
    eval $@ > $file
    xterm -e $PAGER $file
    rm $file
}

if [ -f $HOME/.vlaunchrc ]; then
    source $HOME/.vlaunchrc
fi
if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME=$HOME/.config
fi
if [ -f $XDG_CONFIG_HOME/vlaunchrc ]; then
    source $XDG_CONFIG_HOME/vlaunchrc
fi
if [ -f "$VLAUNCHRC" ]; then
    source $VLAUNCHRC
fi

if [ -z "$(eval "echo \$$1")" ]; then
    echo 1>&2 "$0 cammand not found: $1"
    exit 37
fi

exec $(eval "echo \$$1")

