#!/usr/bin/env bash

### detect dotfileswgh snippet
if [ -z "$DOTFILESWGH" ]; then
    if [ -d "$HOME/dotfileswgh" ]; then
        export DOTFILESWGH="$HOME/dotfileswgh"
    elif [ -d /rootgit/base.rootgit/dotfileswgh ]; then
        export DOTFILESWGH=/rootgit/base.rootgit/dotfileswgh
    fi
fi
export DOTFILESWGH="${DOTFILESWGH:-$HOME/dotfileswgh}"

source $DOTFILESWGH/env-more-with-mixins.sh

exec "$@"
