#!/usr/bin/env bash

if [[ "$@" =~ "--help" ]]; then
    echo "Usage: $0 [--start]"
    echo "Generate xsettingsd config from dotfileswgh and reload or start xsettingsd."
    echo "With --start, exec xsettingsd with the generated config."
    echo "Without --start, send SIGHUP to a running xsettingsd to reload settings."
    exit 0
fi

configdir=${XDG_RUNTIME_DIR:-/tmp/$USER/xsettingsd}

themeconfig=$DOTFILESWGH/xsettingsd-$(lightdark-status)
mkdir -p $configdir
cat $DOTFILESWGH/xsettingsd-base $themeconfig >$configdir/xsettingsd-config

if [[ "$1" = "--start" ]]; then
    exec xsettingsd -c $configdir/xsettingsd-config
else
    # xsettingsd reloads its settings when it gets SIGHUP
    killall -HUP xsettingsd
fi

