#!/usr/bin/env bash

reload=1
if [[ "$1" = "--settings-only" ]]; then
     reload=0
fi

themeconfig=$DOTFILESWGH/xsettingsd-$(lightdark-status)
mkdir -p $HOME/.config/xsettingsd
cat $DOTFILESWGH/xsettingsd-base $themeconfig >$HOME/.config/xsettingsd/xsettingsd.conf

if [[ "$reload" = 1 ]]; then
    # xsettingsd reloads its settings when it gets SIGHUP
    killall -HUP xsettingsd
fi

