#!/bin/sh
UNAME=`uname`
DIRCOLORS_FILE="$DOTFILESWGH/dircolors-gen-dark"
if test "$(lightdark-status)" = "light"; then
    DIRCOLORS_FILE="$DOTFILESWGH/dircolors-gen-light"
fi

eval `dircolors -b $DIRCOLORS_FILE`
BSD="no"
if test "$UNAME" = FreeBSD -o "$UNAME" = Darwin; then
    BSD="yes"
fi
if test "$BSD" = yes -a ! -d /run/current-system/sw/bin ; then
    exec ls -G "$@"
else
    exec ls --color=auto "$@"
fi
