#!/bin/sh
UNAME=`uname`
DIRCOLORS_FILE="$DOTFILESWGH/dircolors-dark"
if test "$(lightdark-status)" = "light"; then
    DIRCOLORS_FILE="$DOTFILESWGH/dircolors-light"
fi

eval `dircolors -b $DIRCOLORS_FILE`
if test "$UNAME" = FreeBSD -o "$UNAME" = Darwin; then
    exec ls -G "$@"
else
    exec ls --color=auto "$@"
fi
