#!/bin/sh
UNAME=`uname`
DIRCOLORS_FILE="$DOTFILESWGH/dircolors-gen-dark"
if test "$(lightdark-status)" = "light"; then
    DIRCOLORS_FILE="$DOTFILESWGH/dircolors-gen-light"
fi

eval `dircolors -b $DIRCOLORS_FILE`
if test "$UNAME" = FreeBSD -o "$UNAME" = Darwin; then
    exec ls -GlaFH "$@"
else
    exec ls --color=auto -laFh "$@"
fi
