#!/usr/bin/env bash

if [[ -z "$1" || "$@" =~ "--help" ]]; then
    echo "usage: $0 <profile>"
    exit
fi
if [[ "$1" = "--new" ]]; then
    new=true
    shift
fi
prof="$1"
shift

# MOZ_ENABLE_WAYLAND seems to be on by default, setting it to 0 forces it to run through xwayland.  In xwayland it doesn't pick up styling properly, but it doesn't crash every time I plug in/out a USB device.  I've read other opinions that Firefox isn't very stable on Wayland as well.
#if [[ -n "$WAYLAND_DISPLAY" ]]; then
#    export MOZ_ENABLE_WAYLAND=0
#fi


FFX=${FFX:-firefox}
profile="$DOTFILESWGH_DOTLOCAL/firefox-profiles/firefox-profile_$prof"

if [[ "$new" = "true" ]]; then
    mkdir -p "$profile"
    pushd "$profile"
    ln -s "$DOTFILESWGH/firefox-user.js" user.js
    # TODO - consider a flag to NOT install any preferences, to have total vanilla setup.  I can just manually make an empty directory to do this, though.
    # TODO - consider auto-installing some extensions, since default firefox is unfortunately missing things that should be core functionality of a proper user agent...
    # TODO - is there a good way to install firefox with NixOS with a set of extensions pre-loaded?
    popd
fi

if [[ -d "$profile" ]]; then
    exec nice -n 5 $FFX --profile $profile "$@"
fi

echo "profile does not exist"
exit 1

