#!/usr/bin/env bash

if [[ -z "$1" ]]; then
    echo "usage: $0 <profile>"
    exit
fi
prof="$1"
shift

FFX=${FFX:-firefox}
profile="$DOTFILESWGH/dotlocal/firefox-profiles/firefox-profile_$prof"
mkdir -p "$profile"

exec nice -n 5 $FFX --profile $profile "$@"
