#!/bin/sh
git remote update && git rebase && git submodule init && git submodule update && git submodule foreach --recursive git submodule init && git submodule foreach --recursive git submodule update
