#!/usr/bin/env bash

# I want to see all local and remote refs, except NOT the gh-pages remote branch!!
# The gh-pages branch tends to take up my whole screen (plus much more) and I never care about it.

#gitRoot="$(git rev-parse --show-toplevel)"
gitRefsAll="$(git show-ref | cut -d ' ' -f 2 | sed s+refs/heads/++ | sed s+refs/remotes/++ | sed s+refs/tags/++)"
gitRefsUse="$(echo "$gitRefsAll" | grep -v gh-pages)"
gitRefsUseFileTemplate="${XDG_RUNTIME_DIR:-/tmp}/gitRefsUseFile.tmp.XXXXXXXXXX"
gitRefsUseFile="$(mktemp "$gitRefsUseFileTemplate")"
echo "$gitRefsUse" > "$gitRefsUseFile"

# Note that here-docs can include parameter substitution unless the end tag is quoted
source=$(cat <<EOSOURCE
(progn
  (require 'magit)
  (wgh/add-buffer-to-kill-block-list
   (magit-log-other
     ;; refs
     (let ((refs-string
            (with-temp-buffer
              (insert-file-contents "$gitRefsUseFile")
              (buffer-string))))
       (split-string refs-string))
     ;; display options
     '("--graph"
       "--decorate"
       "-n256"
       ;; adding ++header shows author, committer, and a bit of the commit message (beyond the headline).  More specifically, it shows info based on magit-log-revision-headers-format
       ;;"++header"
       )
    ))
  (delete-other-windows)
  )
EOSOURCE
)
#exec premacs-use-t --eval "(progn (wgh/add-buffer-to-kill-block-list (call-interactively 'magit|log-all)) (delete-other-windows) )"
premacs-use-maybe --eval "$source"
rm "$gitRefsUseFile"
