#!/usr/bin/env bash

if [ '!' -d $WGHHOME/.prifsb ]; then
  mkdir -p $WGHHOME/.prifsb $WGHHOME/prifsb &&
  chmod 700 $WGHHOME/.prifsb $WGHHOME/prifsb ||
  exit 1
fi
encfs $WGHHOME/.prifsb $WGHHOME/prifsb

