#!/usr/bin/env bash
color="$1"
shift
if test "$color" = "$TMUX_COLOR"; then
    cd ~
    TMUX="" thm new-session -d -s "$@"
    thm switch-client -t "$@"
else
    export TMUX_COLOR="$color"
    export TMUX_FG_COLOR="$(tmux-text-color-for-bg-color $color)"
    exec thm new-session -s "$@"
fi
