#!/bin/sh
if test "blue" = "$TMUX_COLOR"; then
    cd ~
    TMUX="" tm new-session -d -s "$@"
    tm switch-client -t "$@"
else
    unset TMUX
    export TMUX_COLOR=blue
    export TMUX_FG_COLOR="#ffffff"
    exec tm new-session -s "$@"
fi
