#!/usr/bin/env bash

# This was originally an alias, but I wanted to put it as my $EDITOR.
# $EDITOR works best when the command is one word - no spaces.  So it's
# best for it to be a wrapper script.

if [[ "$TERM" = "alacritty-direct" ]]; then
   # vim doesn't seem to play well with the alacritty-direct terminfo right now.
   TERM=xterm
fi
exec vim -u $DOTFILESWGH/vimrc "$@"

