#!/usr/bin/zsh

# nuke viins map, replacing it with the contents of the emacs map
bindkey -A emacs viins

# escapes for command mode
bindkey -M viins 'jk' vi-cmd-mode
bindkey -M viins 'kj' vi-cmd-mode


function zle-line-init zle-keymap-select {

    RPS1="${${KEYMAP/vicmd/CMD}/(main|viins)/INS}"
    echo hello
    if [ "$RPS1" = "CMD" ]
    then
        RPS1="%F{cyan}[CMD]"
    elif [ "$RPS1" = "INS" ]
    then
        RPS1="%F{magenta}[INS]"
    fi
    RPS2=$RPS1
    zle reset-prompt
}

# this is bugging me for now, because it adds extra newlines
#zle -N zle-line-init
#zle -N zle-keymap-select


# use viins, which is now emacs-y, but has an out to vicmd mode
bindkey -v


# todo -- opp.zsh adds surround functionality, and some plugins by tarao add more still (and have emacs counterparts that I need to check out)

