#!/usr/bin/env bash

BUILD_TYPE=Release
#BUILD_TYPE=RelWithDebInfo
cmake -G Ninja -B ../iree-build/ -DIREE_BUILD_PYTHON_BINDINGS=ON -DPython3_EXECUTABLE="$(which python3)" -DIREE_HAL_DRIVER_HID=ON -DIREE_TARGET_BACKEND_ROCM=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
